### ISSUE TITLE
Deployment seems to not work

### ISSUE THREAD

**Issue by JanPietrzyk** [infection/site#126]
Hi,

I just noticed that the site is older then the sources (at least of the master) would suggest. So something seems to be broken in the deployment pipeline...

https://github.com/infection/site/blob/master/src/guide/installation.md - shows infection 0.12
https://infection.github.io/guide/installation.html - shows 0.8

**Comment by borNfreee** [comment]
Hi,

could you please try clearing ServiceWorker cache please? Or try Incognito? 

I see 0.12 on https://infection.github.io/guide/installation.html

We have removed the ServiceWorker support since it was very buggy https://github.com/infection/site/commit/853ce699af8f12adb7c13069832ec05a7b6cb765

But it's possible that your browser still has a cache

**Comment by JanPietrzyk** [comment]
Fascinating :D Tanks a lot,  just a cache issue

**Comment by BackEndTea** [comment]
@borNfreee Maybe we could push some kind of 'cache-buster' service worker, which clears out all the cache it has? I'm not sure how to go about that for this site though.

**Comment by borNfreee** [comment]
Good idea. https://github.com/infection/site/issues/127 at least we will try that ;)
