### ISSUE TITLE
Add italian translation

### ISSUE THREAD

**Issue by FedericoBiccheddu** [infection/site#9]
Hi @borNfreee, I would like to contribute with the italian translation.

Are you ok with this or do you prefer to keep all in English?

**Comment by borNfreee** [comment]
Hi @FedericoBiccheddu !

The main concern about any translations is they are often out of date. 

Since I don't know Italian, the question is: who will translate the new documentation? Are you going to support next releases or do you want to translate just current documentation?

The second point is how we can handle it on infection.github.io/guide/ - new dropdown with languages? I'm a newbie with `hexo` engine which is used to generate our static documentation. So if you are comfortable with investigating it - this is ok. **UPD:** found it in vue.js site which this site was cloned from: https://vuejs.org/

PS: just curious, don't Italian developers learn
English? :) I mean, what is the percentage are you going to cover from all developers translating English to Italian? If the percentage is too small, maybe it doesn't worth it?

I'm always open to any contributions, but wanted to raise these questions to think twice before starting ;)

**Comment by FedericoBiccheddu** [comment]
Hi @borNfreee ,

the question about percentage is the main one and the answer is **_not enough_**.

Probably the first step to do is to make known what mutation testing is and why it's helpful.

If you agree we can close this issue.

**Comment by borNfreee** [comment]
Anyway, thank you @FedericoBiccheddu
